#!/bin/bash
# ex3modules - Makefiles for installing software on the eX3 cluster
# Copyright (C) 2021 James D. Trotter
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# Authors: James D. Trotter <james@simula.no>
#
# This script builds and installs software packages and Environment
# Modules scripts on the eX3 cluster.
#
# Example usage:
#
#  $ ./ex3modules --prefix=/work/${USER}/ex3modules

set -o errexit

program_name=ex3modules
program_version=0.5.0

# default options
with_cmake=cmake-3.17.2
with_mpi=openmpi-4.0.5
with_openssl=openssl-1.1.1c
with_python=python-3.7.4
with_slurm=slurm-20.02.7

function help()
{
    printf "Usage: ${0} [OPTION]..\n"
    printf " Build and install software packages and Environment Modules scripts for eX3\n"
    printf "\n"
    printf " Options are:\n"
    printf "  %-20s\t%s\n" "--prefix=PREFIX" "install files in PREFIX"
    printf "  %-20s\t%s\n" "--pkgsrcdir=DIR" "package sources [PREFIX/src]"
    printf "  %-20s\t%s\n" "--pkgdir=DIR" "installed packages [PREFIX/pkgs]"
    printf "  %-20s\t%s\n" "--modulefilesdir=DIR" "Environment Modules scripts [PREFIX/modulefiles]"
    printf "\n"
    printf "  %-20s\t%s\n" "--list-packages" "list available packages"
    printf "  %-20s\t%s\n" "--describe-package" "describe packages"
    printf "\n"
    printf "  %-20s\t%s\n" "--enable-cuda" "build with CUDA support"
    printf "  %-20s\t%s\n" "--enable-gfortran" "build and use internal Fortran compiler"
    printf "  %-20s\t%s\n" "--with-cmake=DIR" "Root directory of CMake installation, or 'cmake-3.17.2'."
    printf "  %-20s\t%s\n" ""               "If a directory is given, then an external CMake is used. In this case,"
    printf "  %-20s\t%s\n" ""               "DIR/bin is added to PATH. Otherwise, an internal CMake is used."
    printf "  %-20s\t%s\n" ""               "[defaults to 'cmake-3.17.2']"
    printf "  %-20s\t%s\n" "--without-cmake" "disable CMake usage completely. Some modules may not be built."
    printf "  %-20s\t%s\n" "--with-mpi=DIR" "Root directory of MPI installation, or one of the following values:"
    printf "  %-20s\t%s\n" ""               "'openmpi-4.0.5', 'openmpi-cuda-4.0.5', 'mpich-3.3.2' or 'mvapich-2.3.4'."
    printf "  %-20s\t%s\n" ""               "If a directory is given, then an external MPI is used, and DIR/include,"
    printf "  %-20s\t%s\n" ""               "DIR/lib and DIR/lib64 are added to search paths for headers and libraries."
    printf "  %-20s\t%s\n" ""               "Otherwise, an internal MPI implementation is built and used. Note that"
    printf "  %-20s\t%s\n" ""               "[defaults to 'openmpi-4.0.5']"
    printf "  %-20s\t%s\n" "--without-mpi" "disable MPI usage completely. Some modules may not be built."
    printf "  %-20s\t%s\n" "--with-openssl=DIR" "Root directory of OpenSSL installation, or 'openssl-1.1.1c'."
    printf "  %-20s\t%s\n" ""               "If a directory is given, then an external OpenSSL is used. In this case,"
    printf "  %-20s\t%s\n" ""               "DIR/bin, DIR/include, DIR/lib and DIR/lib64 are added to search paths for"
    printf "  %-20s\t%s\n" ""               "binaries, headers and libraries. Otherwise, an internal OpenSSL is used."
    printf "  %-20s\t%s\n" ""               "[defaults to 'openssl-1.1.1c']"
    printf "  %-20s\t%s\n" "--without-openssl" "disable OpenSSL usage completely"
    printf "  %-20s\t%s\n" "--with-python=DIR" "Root directory of Python installation, or 'python-3.7.4'."
    printf "  %-20s\t%s\n" ""               "If a directory is given, then an external Python is used. In this case,"
    printf "  %-20s\t%s\n" ""               "DIR/bin, DIR/include, DIR/lib and DIR/lib64 are added to search paths for"
    printf "  %-20s\t%s\n" ""               "binaries, headers and libraries. Otherwise, an internal Python is used."
    printf "  %-20s\t%s\n" ""               "[defaults to 'python-3.7.4']"
    printf "  %-20s\t%s\n" "--without-python" "disable Python usage completely. Some modules may not be built."
    printf "  %-20s\t%s\n" "--with-slurm=DIR" "Root directory of Slurm installation, or 'slurm-20.02.7'."
    printf "  %-20s\t%s\n" ""               "If a directory is given, then an external Slurm is used. In this case,"
    printf "  %-20s\t%s\n" ""               "DIR/bin, DIR/include, DIR/lib and DIR/lib64 are added to search paths for"
    printf "  %-20s\t%s\n" ""               "binaries, headers and libraries. Otherwise, an internal Slurm is used."
    printf "  %-20s\t%s\n" ""               "[defaults to 'slurm-20.02.7']"
    printf "  %-20s\t%s\n" "--without-slurm" "disable Slurm usage completely."
    printf "\n"
    printf "  %-20s\t%s\n" "-v, --verbose" "be more verbose"
    printf "  %-20s\t%s\n" "-h, --help" "display this help and exit"
    printf "  %-20s\t%s\n" "--version" "display version information and exit"
    printf "\n"
    printf " Any additional options are passed on to make.\n"
    printf "\n"
    printf " Report bugs to: <james@simula.no>.\n"
}

function version()
{
    printf "%s %s\n" "${program_name}" "${program_version}"
    printf "Copyright (C) 2021 James D. Trotter\n"
    printf "License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>\n"
    printf "This is free software: you are free to change and redistribute it.\n"
    printf "There is NO WARRANTY, to the extent permitted by law.\n"
}

function list_packages()
{
    make list-packages
}

function describe_packages()
{
    while [ "$#" -gt 0 ]; do
	make "${1}-describe"
	shift 1
    done
}

function parse_program_options()
{
    # Default options
    EXTRA_OPTIONS=()

    # Parse program options
    while [ "$#" -gt 0 ]; do
	case "${1}" in
	    -h | --help) help; exit 0;;
	    --version) version; exit 0;;
	    --list-packages) list_packages; exit 0;;
	    --describe-package) describe_package=1; shift 1;;
	    --prefix) prefix="${2}"; shift 2;;
	    --prefix=*) prefix="${1#*=}"; shift 1;;
	    --pkgscdir) pkgscdir="${2}"; shift 2;;
	    --pkgscdir=*) pkgscdir="${1#*=}"; shift 1;;
	    --pkgdir) pkgdir="${2}"; shift 2;;
	    --pkgdir=*) pkgdir="${1#*=}"; shift 1;;
	    --modulefilesdir) modulefilesdir="${2}"; shift 2;;
	    --modulefilesdir=*) modulefilesdir="${1#*=}"; shift 1;;
	    --enable-cuda) enable_cuda=1; shift 1;;
	    --enable-gfortran) enable_gfortran=1; shift 1;;
	    --with-cmake) with_cmake="${2}"; shift 2;;
	    --with-cmake=*) with_cmake="${1#*=}"; shift 1;;
	    --without-cmake) with_cmake= ; shift 2;;
	    --with-mpi) with_mpi="${2}"; shift 2;;
	    --with-mpi=*) with_mpi="${1#*=}"; shift 1;;
	    --without-mpi) with_mpi= ; shift 2;;
	    --with-openssl) with_openssl="${2}"; shift 2;;
	    --with-openssl=*) with_openssl="${1#*=}"; shift 1;;
	    --without-openssl) with_openssl= ; shift 2;;
	    --with-python) with_python="${2}"; shift 2;;
	    --with-python=*) with_python="${1#*=}"; shift 1;;
	    --without-python) with_python= ; shift 2;;
	    --with-slurm) with_slurm="${2}"; shift 2;;
	    --with-slurm=*) with_slurm="${1#*=}"; shift 1;;
	    --without-slurm) with_slurm= ; shift 2;;
	    -v | --verbose) verbose=1; shift 1;;
	    --) shift; break;;
	    *) EXTRA_OPTIONS+=("${1}"); shift 1;;
	esac
    done
    EXTRA_OPTIONS+="$@"

    set -- "${EXTRA_OPTIONS[@]}"
}

function main ()
{
    parse_program_options "$@"

    # Describe packages
    if [ ! -z "${describe_package}" ]; then
	describe_packages ${EXTRA_OPTIONS[@]}
	exit 0
    fi

    echo "Installing modules to ${prefix:-.}" >&2

    make_options=""
    [ ! -z "${prefix}" ] && make_options+=" prefix=${prefix}"
    [ ! -z "${pkgsrcdir}" ] && make_options+=" pkgsrcdir=${pkgsrcdir}"
    [ ! -z "${pkgdir}" ] && make_options+=" pkgdir=${pkgdir}"
    [ ! -z "${modulefilesdir}" ] && make_options+=" modulefilesdir=${modulefilesdir}"
    [ ! -z "${enable_cuda}" ] && make_options+=" ENABLE_CUDA=1"
    [ ! -z "${enable_gfortran}" ] && make_options+=" ENABLE_GFORTRAN=1"
    [ ! -z "${with_cmake}" ] && make_options+=" WITH_CMAKE=${with_cmake}"
    [ ! -z "${with_mpi}" ] && make_options+=" WITH_MPI=${with_mpi}"
    [ ! -z "${with_openssl}" ] && make_options+=" WITH_OPENSSL=${with_openssl}"
    [ ! -z "${with_python}" ] && make_options+=" WITH_PYTHON=${with_python}"
    [ ! -z "${with_slurm}" ] && make_options+=" WITH_SLURM=${with_slurm}"
    make ${make_options} ${EXTRA_OPTIONS[@]}
}

main "$@"
